name: todoey
description: A new Flutter project.

publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^4.1.0
  # official recommended state management method
  provider: ^6.0.1
  # sqlite related lib
  sqflite: ^2.0.0+4
  path_provider: ^2.0.5
  sqlbrite: ^2.2.0
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

